

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vishal Yadav
 */
public class DigitalClock extends javax.swing.JFrame {
      
    
    private Timer timer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DigitalClock.class.getName());

    /**
     * Creates new form DigitalClock
     */
    public DigitalClock() {
        initComponents();
       timer = new Timer(10, e -> updateTime());
        timer.start();
    }

    // ✅ TIME + DATE UPDATE
    private void updateTime() {

        Date now = new Date();

        // Time with milliseconds
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss a");
        timelabel.setText(timeFormat.format(now));

        // Date
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEE, dd-MM-yyyy");
        datelabel.setText(dateFormat.format(now));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(135, 149, 148));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 208, -1));

        datelabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        datelabel.setForeground(new java.awt.Color(255, 204, 153));
        datelabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        datelabel.setLabelFor(datelabel);
        datelabel.setText("Date");
        datelabel.setToolTipText("");
        jPanel1.add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 240, -1));

        timelabel.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        timelabel.setForeground(new java.awt.Color(255, 255, 255));
        timelabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timelabel.setText("00 : 00 : 00");
        jPanel1.add(timelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 400, 39));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Hr");
        jLabel2.setAutoscrolls(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 30, -1));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Min");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Sec");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 530, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DigitalClock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel timelabel;
    // End of variables declaration//GEN-END:variables
}
